# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hywel Stoakes
email: hywel |dot| stoakes | at | gmail |dot| com
description: > # this means to ignore newlines until "baseurl:"
  A blog to record musings about language and speech.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hywel.github.io" # the base hostname & protocol for your site
twitter_username: hywel_
github_username:  hywel

# Build settings
markdown: kramdown
