baseurl:
title: Hywel Stoakes
subtitle: Phonetics and beyond
author: hywel stoakes
simple_search: https://duckduckgo.com
description: A Jekyll theme that uses the Tuft theme by Clay Harmon
name: tufte
markdown: Kramdown
kramdown:  
  input: GFM
  syntax_highlighter: pygments
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: pygments
permalink: /articles/:short_year/:title
timezone: Australia/Melbourne
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master